---
- hosts: all
  pre_tasks:
    - name: "Installing which"
      action: yum
              name={{ item }}
              state=installed
      with_items:
        - net-tools
        - which
        - libselinux-python
      register: installation_dependencies
    - name: "Add zabbix.example.com to hosts file."
      action: shell echo '127.0.0.1 zabbix.example.com' >> /etc/hosts
      when: installation_dependencies.changed
    - name: "Make sure we can sudo in the deployment"
      lineinfile: dest=/etc/sudoers line="Defaults    !requiretty" state=present
      when: installation_dependencies.changed
    - name: "Make sure the docs are installed to"
      lineinfile: dest=/etc/yum.conf line="tsflags=nodocs" state=absent
      when: installation_dependencies.changed

  roles:
    - role: galaxyprojectdotorg.postgresql
      when: inventory_hostname in groups['postgresql']
    - role: geerlingguy.mysql
      when: inventory_hostname in groups['mysql']
    - role: ansible-zabbix-server
