---
# task file for postgresql

- name: "Set the correct delegated_dbhost (to support postgres db deployment on a remote dbhost)"
  set_fact:
    delegated_dbhost: "{{ server_dbhost if (server_dbhost != 'localhost') else inventory_hostname }}"

- name: "PostgreSQL | Create database"
  postgresql_db:
    name: "{{ server_dbname }}"
    port: "{{ server_dbport }}"
    state: present
  become: yes
  become_user: postgres
  delegate_to: "{{ delegated_dbhost }}"
  when: zabbix_database_creation
  tags:
    - zabbix-server
    - database

- name: "PostgreSQL | Create database user"
  postgresql_user:
    db: "{{ server_dbname }}"
    name: "{{ server_dbuser }}"
    password: "{{ server_dbpassword }}"
    port: "{{ server_dbport }}"
    priv: ALL
    state: present
  become: yes
  become_user: postgres
  delegate_to: "{{ delegated_dbhost }}"
  when: zabbix_database_creation
  tags:
    - zabbix-server
    - database

- name: "PostgreSQL | Create schema"
  shell: "cd {{ datafiles_path }} && if [ -f create.sql.gz ]; then gunzip create.sql.gz ; fi && psql -h '{{ server_dbhost }}' -U '{{ server_dbuser }}' -d '{{ server_dbname }}' -p '{{ server_dbport }}' -f create.sql && touch /etc/zabbix/schema.done"
  args:
    creates: /etc/zabbix/schema.done
  environment:
    PGPASSWORD: '{{ server_dbpassword }}'
  when: zabbix_short_version >= 30 and zabbix_database_sqlload
  tags:
    - zabbix-server
    - database

- name: "PostgreSQL | Importing schema file"
  shell: "cd {{ datafiles_path }} && if [ -f schema.sql.gz ]; then gunzip schema.sql.gz ; fi && psql -h '{{ server_dbhost }}' -U '{{ server_dbuser }}' -d '{{ server_dbname }}' -p '{{ server_dbport }}' -f schema.sql && touch /etc/zabbix/schema.done"
  args:
    creates: /etc/zabbix/schema.done
  environment:
    PGPASSWORD: '{{ server_dbpassword }}'
  when: (zabbix_short_version < 30 and zabbix_database_sqlload) or (zabbix_repo == "epel" and zabbix_database_sqlload)
  tags:
    - zabbix-server
    - database

- name: "PostgreSQL | Importing images file"
  shell: "cd {{ datafiles_path }} && psql -h '{{ server_dbhost }}' -U '{{ server_dbuser }}' -d '{{ server_dbname }}' -p '{{ server_dbport }}' -f images.sql && touch /etc/zabbix/images.done"
  args:
    creates: /etc/zabbix/images.done
  environment:
    PGPASSWORD: '{{ server_dbpassword }}'
  when: (zabbix_short_version < 30 and zabbix_database_sqlload) or (zabbix_repo == "epel" and zabbix_database_sqlload)
  tags:
    - zabbix-server
    - database

- name: "PostgreSQL | Importing data file"
  shell: "cd {{ datafiles_path }} && psql -h '{{ server_dbhost }}' -U '{{ server_dbuser }}' -d '{{ server_dbname }}' -p '{{ server_dbport }}' -f data.sql && touch /etc/zabbix/data.done"
  args:
    creates: /etc/zabbix/data.done
  environment:
    PGPASSWORD: '{{ server_dbpassword }}'
  when: (zabbix_database_sqlload and zabbix_short_version < 30) or (zabbix_repo == "epel" and zabbix_database_sqlload)
  tags:
    - zabbix-server
    - database
